dhis2/expression-parser

pom.xml
src/main/java/org/hisp/dhis/lib/expression/math/GS1Elements.java
src/main/java/org/hisp/dhis/lib/expression/math/ZScoreTable.java

Just a couple of fixes for Android
- They need ZScoreTable to be public in order to draw the in the app
- One fix in the GS1 elements was lost in the process of made the parser work with rule engine

Fixes for android client

---

.github/workflows/master.yml

This PR fixes a defect in the branch `kmp-structure` that prevents the `master.yml` action from starting.

Replace 'with' by 'env' in master github workflow

---

.github/workflows/main.yml
.github/workflows/master.yml

The task `test` only runs test for JVM by default. The task `allTests` should be used instead.

Enable all tests

---

.gitignore
src/commonMain/kotlin/org/hisp/dhis/lib/expression/ast/Typed.kt
src/commonMain/kotlin/org/hisp/dhis/lib/expression/ast/UnaryOperator.kt
src/commonTest/kotlin/org/hisp/dhis/lib/expression/MathExpressionTest.kt
src/commonTest/kotlin/org/hisp/dhis/lib/expression/ast/UnaryOperatorTest.kt

The issue was twofold:
1. JS did not evaluate `value is Int` to false for a double value so it went the integer path and did `-value.toInt()`
2. the `negate` function always had returned a double no matter the input which was important in some calculations to keep doing math for bigger numbers

fix: unary negate of numbers in JS

---

src/commonMain/kotlin/org/hisp/dhis/lib/expression/Expression.kt
src/jsMain/kotlin/org.hisp.dhis.lib.expression.js/ExpressionJs.kt

It appears that `ExpressionFunctions` cannot be implemented in Java by only overriding the abstract function and those that should be overridden. Therefore only the behaviour of the "undefined function name" function is exposed.

fix: hide ExpressionFunctions inside Expression

---

.github/workflows/job-publish.yml
.nyx.yaml
settings.gradle.kts

Enables the publication of github releases on every beta or main publication. Release are created as:
- beta branch -> pre-release
- main branch -> release
The PRs separates the Nyx configuration to its own file instead of using the defaults presets. In this way, we have more control on the behavior.

fix: separate Nyx config file

---

.github/workflows/scripts/publish-npm.sh
build.gradle.kts
buildSrc/src/main/kotlin/npm-publish-conventions.gradle.kts

This PR adds the capability to ship both module types (esmodule and commonjs) together. Files are located in the same folder with same names and different extensions (`.js` for commonjs and `.mjs` for esmodule).
The solution was to conditionally trigger esmodule build or commonjs build depending on a parameter (`-PuseCommonJs`). By default it uses esmodule. The publish script runs two builds and their output files are sent to the same output folder.

fix: ship esmodule and commonjs

---

src/commonMain/kotlin/org/hisp/dhis/lib/expression/ast/NamedFunction.kt
src/commonMain/kotlin/org/hisp/dhis/lib/expression/eval/Calculator.kt
src/commonMain/kotlin/org/hisp/dhis/lib/expression/spi/ExpressionFunctions.kt
src/commonMain/kotlin/org/hisp/dhis/lib/expression/syntax/ExpressionGrammar.kt
src/commonTest/kotlin/org/hisp/dhis/lib/expression/function/ContainsItemsTest.kt
src/commonTest/kotlin/org/hisp/dhis/lib/expression/function/ContainsTest.kt

This PR adds two expression functions:
* `contains(expr, ...)` returns true if the first expr contains each of the following expressions as a substring.
* `containsItems(expr, ...)` returns true if the first expr is split into tokens separated by commas, and each of the following expressions exactly matches one of the tokens.
See [DHIS2-16211](https://dhis2.atlassian.net/browse/DHIS2-16211) for more details and examples.
Each new function is covered with unit tests.
[DHIS2-16211]: https://dhis2.atlassian.net/browse/DHIS2-16211?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat: contains and containsItems [DHIS2-16211]

---

buildSrc/src/main/kotlin/maven-publish-conventions.gradle.kts

Related to this issue: https://github.com/gradle/gradle/issues/26091

fix: Apply workaround to signing multiplatform projects

---

buildSrc/src/main/kotlin/maven-publish-conventions.gradle.kts

Related to this issue: https://github.com/gradle/gradle/issues/26091

fix: Apply workaround to signing multiplatform projects (#57)

---

buildSrc/src/main/kotlin/maven-publish-conventions.gradle.kts

Nexus requires a javadoc artifact

fix: modify javadoc classifier

---

buildSrc/src/main/kotlin/maven-publish-conventions.gradle.kts

Nexus requires a javadoc artifact

 fix: Modify javadoc classifier 

---

.github/workflows/scripts/publish-npm-prod.sh

The script to deploy the JS library to NPMJS (production mode) was missing the property to remove the SNAPSHOT suffix.
This PR does not generate a new version.

[skip publish] Remove SNAPSHOT suffix from production release to NPMJS

---

build.gradle.kts
src/commonMain/kotlin/org/hisp/dhis/lib/expression/Expression.kt
src/commonMain/kotlin/org/hisp/dhis/lib/expression/ast/Typed.kt
src/commonTest/kotlin/org/hisp/dhis/lib/expression/VariableExpressionTest.kt
src/commonTest/kotlin/org/hisp/dhis/lib/expression/ast/TypedTest.kt

The central idea is to use `value.toEpochDays().toDouble()` when `value` is a `LocalDate` that should become a number to be used in a comparison or math operation.
While doing this I noticed that when coercing a `VariableValue` we use the raw `String` `value` without considering the `ValueType` of the variable first. I changed this by calling `toMixedTypeTypeCoercion` for variables first, which unpacks the value according to the `ValueType`. That result is the coerced by recursively calling the target coercion function on it, for example for a number:
```kotlin
if (value is VariableValue) return toNumberTypeCoercion(toMixedTypeTypeCoercion(value))
```
Since `LocalDate` has `toEpochDays` (instead of the more usual epoch milliseconds) I used this. If we want millisecond precision we need to …

feat: data comparison and coercion [DHIS2-18785]

---

build.gradle.kts
src/commonMain/kotlin/org/hisp/dhis/lib/expression/eval/Calculator.kt
src/commonTest/kotlin/org/hisp/dhis/lib/expression/operator/LogicalExpressionTest.kt

When evaluating `a && b` or `a || b` b should only be evaluated when needed to determine the result. Meaning, `false && b` is always `false` and `true || b` is always `true` so `b` is not evaluated in such cases. 
Added a test scenario based on the issue encountered by Pablo where `d2:daysBetween` fails for `null` arguments. Then a `&&` and an `||` guard is used with `d2:hasValue` to show that without the guard the failure is raised but with the guard it does compute without raising the failure of a `null` value argument.

feat: short-circuiting for AND and OR operators [DHIS2-18849]

---

.gitignore
build.gradle.kts
buildSrc/build.gradle.kts
buildSrc/settings.gradle.kts
gradle/libs.versions.toml

Creation of a gradle version catalog. It doesn't modify any version, just moves the dependency definition to the file `gradle/libs.versions.toml`.
The PR uses the syntax "group + name + versionRef", such as:
`ionspin-bignum = { group = "com.ionspin.kotlin", name = "bignum", version.ref = "bignum" }`
but there are many other syntax allowed. Up to you if you prefer other one ([check this](https://docs.gradle.org/current/userguide/version_catalogs.html#libraries)).

[skip publish] chore: create version catalog

---

build.gradle.kts
src/commonMain/kotlin/org/hisp/dhis/lib/expression/math/GS1Elements.kt
src/commonTest/kotlin/org/hisp/dhis/lib/expression/math/GS1ElementsTest.kt

The logic handling names with `*` would get confused because of `ai` being changed half way though. 
The fix is just based on assumptions of how the function should work.

fix: getApplicationIdentifier logic for *

---

.github/workflows/main.yml
.github/workflows/publish_npm_beta.yml
.github/workflows/pull_request.yml
.github/workflows/scripts/build-npm-package.sh
.github/workflows/scripts/publish-npm-beta.sh
.github/workflows/scripts/publish-npm-prod.sh
build.gradle.kts
gradle/libs.versions.toml
gradle/wrapper/gradle-wrapper.properties
src/commonMain/kotlin/org/hisp/dhis/lib/expression/spi/ValueType.kt

The initial scope of this PR was to upgrade the Kotlin version (2.0.21). As a side effect of this:
- the Gradle version was updated in order to match the recommended version (gradle 8.12).
- because of this, the NPM publish plugin needed to be updated. And as a consequence of this:
- this build script was refactored because of a change of the plugin: in previous versions, the output folder wasn't cleaned between builds, which was used to combine EsModues and CommonJs builds into a same folder (npm hybrid package); in the newest version, the output folder is cleaned between builds, so it is necessary to combine the two builds into a separate folder.
- the Java version used to run gradle was upgraded to 21. **Important: you will have to change the Java version for Gradle in Intellij to Java …

chore: Upgrade kotlin and libs

---

.github/workflows/dokka.yml
README.md
gradle/libs.versions.toml

This PR adds a github action to publish API docs to github pages. So far, the link to the docs will only be accessible in the badge in the README file. I have added a few more badges for Maven Central and NPM.
It updates the dokka version just to be up-to-date.
This PRs does not publish a new release, but it does publish the API docs to github pages.

[skip publish]: Publish KDoc to github pages

---

.github/workflows/main.yml

Adds a job to automatically publish a github release on each publication. The job uses a reusable workflow.
This job generates the release notes and attaches them to the release. The version tag has the 'v' suffix, such as "v1.4.0".

[skip publish] chore: Add a job to publish release to github

---

src/commonMain/kotlin/org/hisp/dhis/lib/expression/syntax/ExpressionGrammar.kt

Adds `d2:condition` to the rule engine expression grammar.

feat: add d2:condition to rule engine grammar

---

.github/workflows/main.yml

Adds the `workflow_dispatch` modifier to the main workflow, so it can be manually run if needed. The `workflow_dispatch` will only work in the `main` branch.

chore: Enable manually triggering main workflow in main branch

---

gradle.properties
src/commonTest/kotlin/org/hisp/dhis/lib/expression/function/HasValueTest.kt

I was wondering if in the context of the ticket this https://github.com/dhis2/expression-parser/blob/main/src/commonMain/kotlin/org/hisp/dhis/lib/expression/syntax/Expr.kt#L346 may be causing issues modelling the name of the variable as `STRING` and not `IDENTIFIER`. I think this is fine. On the parsing level it is correct to make it a `STRING` node as `parseString` is used (allowing any string) whereas an `IDENTIFER` node should originate from `parseIdentifer` (being much more limited). However making the different node types is a burden when handling variables. As far as I can see the child of a variable is mostly handled independent of its type.
I am wondering a bit about this line https://github.com/dhis2/expression-parser/blob/main/src/commonMain/kotlin/org/hisp/dhis/lib/expression/as …

test: tests for different variable syntax [DHIS2-15858]

---

build.gradle.kts
src/commonMain/kotlin/org/hisp/dhis/lib/expression/ast/Typed.kt
src/commonMain/kotlin/org/hisp/dhis/lib/expression/spi/ValueType.kt
src/commonMain/kotlin/org/hisp/dhis/lib/expression/spi/VariableValue.kt

A `null` variable with `ValueType` DATE should always be evaluated to `null` and we shouldn't try to fallback to a default value.
This change will fix https://dhis2.atlassian.net/browse/DHIS2-19199

fix: Remove default value for DATE ValueType variables

---

api/expression-parser.api
build.gradle.kts
src/commonMain/kotlin/org/hisp/dhis/lib/expression/ast/NamedFunction.kt
src/commonMain/kotlin/org/hisp/dhis/lib/expression/eval/Calculator.kt
src/commonMain/kotlin/org/hisp/dhis/lib/expression/spi/ExpressionFunctions.kt
src/commonMain/kotlin/org/hisp/dhis/lib/expression/syntax/ExpressionGrammar.kt
src/commonTest/kotlin/org/hisp/dhis/lib/expression/function/InUserGroupTest.kt

https://dhis2.atlassian.net/browse/DHIS2-19426
PR implements `d2:inUserGroup` function for program rule. 
`d2:inUserGroup('UYXOT4A3SA')` should return true if the current user is a member of this group "`UYXOT4A3SA`"

feat: Add support for d2:inUserGroup function[DHIS2-19426]

---

api/expression-parser.api
build.gradle.kts
src/commonMain/kotlin/org/hisp/dhis/lib/expression/ExpressionMode.kt
src/commonMain/kotlin/org/hisp/dhis/lib/expression/ast/Nodes.kt
src/commonMain/kotlin/org/hisp/dhis/lib/expression/spi/AndroidCustomIntentVariable.kt
src/commonMain/kotlin/org/hisp/dhis/lib/expression/spi/DataItemType.kt
src/commonMain/kotlin/org/hisp/dhis/lib/expression/spi/IDType.kt
src/commonMain/kotlin/org/hisp/dhis/lib/expression/syntax/ExpressionGrammar.kt
src/commonTest/kotlin/org/hisp/dhis/lib/expression/AndroidCustomIntentExpressionTest.kt

This PR adds a new evaluation mode for Android Custom Intents.
There is a predefined list of supported variables (`AndroidCustomIntentVariable`). Their value must be provided by the client using the `ExpressionData.programVariableValues` property. This is an abuse of the model, but it was agreed to use this property to avoid breaking changes in the API.
The mode includes some D2 functions, which are needed in the known use cases of custom intents.

feat: Add AndroidCustomIntent evaluation mode
